# Generated by Django 2.1.2 on 2018-10-21 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BookingPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Booking Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Booking End Date')),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Banner')),
            ],
        ),
        migrations.CreateModel(
            name='PricePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Booking Start Date')),
                ('end_date', models.DateTimeField(verbose_name='Booking End Date')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='banners.Banner')),
            ],
        ),
    ]
