# Generated by Django 2.1.2 on 2018-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingperiod',
            name='end_date',
            field=models.DateField(verbose_name='Booking End Date'),
        ),
        migrations.AlterField(
            model_name='bookingperiod',
            name='start_date',
            field=models.DateField(verbose_name='Booking Start Date'),
        ),
        migrations.AlterField(
            model_name='priceperiod',
            name='end_date',
            field=models.DateField(verbose_name='Price End Date'),
        ),
        migrations.AlterField(
            model_name='priceperiod',
            name='start_date',
            field=models.DateField(verbose_name='Price Start Date'),
        ),
    ]
